# Generated by Django 3.0.3 on 2020-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='bee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='Use these paths to move around', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='Walkway', max_length=50),
        ),
    ]
